version: '3.7'

services:
  web:
    build:
      context: ./docker/php-apache
    container_name: php53_apache
    hostname: test_development
    ports:
      - "8086:80"
      - "443:443"
    volumes:
      - ./html/portal:/var/www/html/test
      - ./portal_inc:/var/www/test
      - ./docker/php-apache/apache/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./docker/php-apache/apache/vhost.conf:/etc/httpd/conf.d/vhost.conf

    depends_on:
      - db

  db:
    image: mysql:5.5
    container_name: mysql55
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data:
